name: Release Windows

on:
  workflow_dispatch:
  release:
    types: published

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build image
      run: docker build . -f pack/Dockerfile.win32 -t qucsrflayout:win32

    - name: Run image
      run: docker run -v $PWD:/workdir/Qucs-RFlayout -t qucsrflayout:win32

    - name: Extract informations
      id: extract
      shell: bash
      run: |
        echo "##[set-output name=tag;]$(echo ${GITHUB_REF##*/})"
        echo "##[set-output name=upload_url;]$(curl -sL https://api.github.com/repos/thomaslepoix/Qucs-RFlayout/releases/tags/${GITHUB_REF##*/} | jq -r '.upload_url')"

    - name: Deploy
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.extract.outputs.upload_url }}
        asset_path: build/out/qucsrflayout-${{ steps.extract.outputs.tag }}-x86_64.zip
        asset_name: qucsrflayout-${{ steps.extract.outputs.tag }}-x86_64.zip
        asset_content_type: application/zip
