name: Release Windows

on:
  workflow_dispatch:
  release:
    types: published

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout
      uses: actions/checkout@v4

    - name: 'Dependencies: Nix'
      uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v4

    - name: Build
      run: nix build -L --no-update-lock-file .#qucsrflayoutMingw64Zip

    - name: Extract informations
      id: extract
      shell: bash
      run: |
        echo "tag=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
        echo "upload_url=$(curl -sL https://api.github.com/repos/thomaslepoix/Qucs-RFlayout/releases/tags/${GITHUB_REF##*/} | jq -r '.upload_url')" >> $GITHUB_OUTPUT

    - name: Deploy .zip on Github
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.extract.outputs.upload_url }}
        asset_path: result/qucsrflayout-x86_64-w64-mingw32-${{ steps.extract.outputs.tag }}.zip
        asset_name: qucsrflayout-${{ steps.extract.outputs.tag }}-x86_64-w64-mingw32.zip
        asset_content_type: application/zip
