name: Release Debian

on:
  workflow_dispatch:
  release:
    types: published

env:
  PACKAGE_NAME: qucs-rflayout

jobs:
  run:
    strategy:
      matrix:
        os:
          - name: ubuntu-20.04
            distro: bullseye,focal
          - name: ubuntu-18.04
            distro: buster,bionic,cosmic,disco,eoan

    runs-on: ${{ matrix.os.name }}

    steps:
    - name: Dependencies
      run: |
        sudo apt update
        sudo apt install -y qt5-default libqt5opengl5-dev texlive-xetex

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      run: cmake -S . -B build

    - name: Build program
      run: cmake --build build

    - name: Build doc
      run: cmake --build build --target doc

    - name: Package
      run: cmake --build build --target package

    - name: Deploy
      run: |
        curl -T build/out/qucsrflayout_${GITHUB_REF##*/}_amd64.deb -uthomaslepoix:${{ secrets.BINTRAY_API_KEY }} https://api.bintray.com/content/open-rflab/debian/${{ env.PACKAGE_NAME }}/${GITHUB_REF##*/}/pool/q/${{ env.PACKAGE_NAME }}/qucsrflayout_${GITHUB_REF##*/}_amd64.deb -H 'X-Bintray-Debian-Distribution: ${{ matrix.os.distro }}' -H 'X-Bintray-Debian-Component: main' -H 'X-Bintray-Debian-Architecture: amd64' -H 'X-Bintray-Publish: 1'
